package k3s

import (
	"fmt"
	"strings"

	"github.com/catalystcommunity/foundry/v1/internal/network"
	"gopkg.in/yaml.v3"
)

// ResolveNodeNetwork verifies the configured node address and pins Flannel to
// the interface that owns it. Call this before starting or restarting K3s.
func ResolveNodeNetwork(executor SSHExecutor, cfg *Config) error {
	if cfg.NodeIP == "" {
		return fmt.Errorf("node_ip is required; refusing K3s address auto-detection")
	}
	if cfg.VIP != "" && cfg.NodeIP == cfg.VIP {
		return fmt.Errorf("node_ip %s equals API VIP", cfg.NodeIP)
	}
	if cfg.FlannelIface == "" {
		iface, err := network.DetectInterfaceForIP(executor, cfg.NodeIP)
		if err != nil {
			return err
		}
		cfg.FlannelIface = iface
	}
	if err := refuseVIPOnFlannelInterface(executor, cfg); err != nil {
		return err
	}
	if cfg.AdvertiseAddress == "" {
		cfg.AdvertiseAddress = cfg.NodeIP
	}
	return nil
}

// refuseVIPOnFlannelInterface fails when the interface Flannel is pinned to also
// carries the API VIP.
//
// Pinning Flannel by interface name is not enough on its own. kube-vip adds the
// VIP as a secondary address on the same NIC that owns the node address, and
// K3s then resolves that interface name to whichever address it picks -- which
// can be the VIP. Peers are then told to send this node's pod traffic to a
// floating address that belongs to the API server role rather than to this
// node, and it silently follows the VIP wherever it moves.
func refuseVIPOnFlannelInterface(executor SSHExecutor, cfg *Config) error {
	if cfg.VIP == "" || cfg.FlannelIface == "" {
		return nil
	}

	addrs, err := network.InterfaceAddresses(executor, cfg.FlannelIface)
	if err != nil {
		// The address list is a cross-check, not the source of truth for the
		// interface; a host that cannot report it is not a reason to refuse to
		// converge.
		return nil
	}

	for _, addr := range addrs {
		if addr == cfg.VIP {
			return fmt.Errorf(
				"interface %s carries both the node address %s and the API VIP %s, "+
					"so Flannel can select the VIP as its VXLAN endpoint and send pod "+
					"traffic to an address that moves between control plane nodes; "+
					"remove the VIP from this cluster or give kube-vip its own interface",
				cfg.FlannelIface, cfg.NodeIP, cfg.VIP)
		}
	}
	return nil
}

const (
	// KubeconfigPath is the default location of the K3s kubeconfig
	KubeconfigPath = "/etc/rancher/k3s/k3s.yaml"

	// RegistriesConfigPath is the location of the registries.yaml file
	RegistriesConfigPath = "/etc/rancher/k3s/registries.yaml"

	// OpenBAO paths for K3s configuration (relative to mount point)
	KubeconfigOpenBAOPath = "k3s/kubeconfig"
	NetworkConfigPath     = "/etc/rancher/k3s/config.yaml.d/10-foundry-network.yaml"
)

// GenerateNetworkConfigYAML pins the identities K3s would otherwise infer from
// the host's address list. In particular, an API VIP must never become a
// Flannel VTEP address.
func GenerateNetworkConfigYAML(cfg *Config, server bool) string {
	lines := []string{"# Generated by Foundry; do not put credentials in this file."}
	if cfg.NodeIP != "" {
		lines = append(lines, "node-ip: "+cfg.NodeIP)
	}
	if cfg.FlannelIface != "" {
		lines = append(lines, "flannel-iface: "+cfg.FlannelIface)
	}
	if server && cfg.AdvertiseAddress != "" {
		lines = append(lines, "advertise-address: "+cfg.AdvertiseAddress)
	}
	return strings.Join(lines, "\n") + "\n"
}

// IndentNetworkConfig formats generated network YAML for dry-run output.
func IndentNetworkConfig(content, prefix string) string {
	lines := strings.Split(strings.TrimSuffix(content, "\n"), "\n")
	return prefix + strings.Join(lines, "\n"+prefix) + "\n"
}

// Registry types (RegistryConfig, RegistryMirror, RegistryAuth, etc.) are generated from CSIL in types.gen.go

// GenerateRegistriesYAML generates the registries.yaml content for K3s
// This configures K3s to use Zot as a pull-through cache for container registries,
// and merges any additional user-defined registry entries.
func GenerateRegistriesYAML(zotURL string, insecure bool, additional []AdditionalRegistry) string {
	rc := RegistryConfig{
		Mirrors: RegistryMirrorMap{
			"docker.io": RegistryMirror{Endpoint: []string{zotURL}},
			"ghcr.io":   RegistryMirror{Endpoint: []string{zotURL}},
		},
		Configs: RegistryAuthMap{},
	}

	// Add zot TLS config
	if insecure {
		insecureTrue := true
		rc.Configs[zotURL] = RegistryAuth{
			Tls: &RegistryTLSConfig{InsecureSkipVerify: &insecureTrue},
		}
	}

	// Merge additional registries
	for _, reg := range additional {
		endpoint := reg.Name
		if reg.Endpoint != nil {
			endpoint = *reg.Endpoint
		}

		// Apply http:// scheme if requested
		if reg.HTTP != nil && *reg.HTTP && !strings.HasPrefix(endpoint, "http") {
			endpoint = "http://" + endpoint
		}

		// Add mirror entry: registry name -> endpoint
		rc.Mirrors[reg.Name] = RegistryMirror{
			Endpoint: []string{endpoint},
		}

		// Build config entry for the endpoint.
		// Auth and TLS are independent — a registry can have both credentials
		// and insecure_skip_verify at the same time.
		auth := RegistryAuth{}
		needsConfig := false

		if reg.Insecure != nil && *reg.Insecure {
			insecureTrue := true
			auth.Tls = &RegistryTLSConfig{InsecureSkipVerify: &insecureTrue}
			needsConfig = true
		}

		if reg.Username != nil && reg.Password != nil {
			auth.Auth = &RegistryAuthConfig{
				Username: reg.Username,
				Password: reg.Password,
			}
			needsConfig = true
		}

		if needsConfig {
			rc.Configs[endpoint] = auth
		}
	}

	out, _ := yaml.Marshal(rc)
	return string(out)
}

// GenerateRegistriesConfig generates registries.yaml content for Zot registry
// This is a convenience wrapper around GenerateRegistriesYAML that assumes
// insecure connections (common for local development)
func GenerateRegistriesConfig(zotAddr string, additional []AdditionalRegistry) string {
	// Format the Zot address as a URL with port
	zotURL := fmt.Sprintf("http://%s:5000", zotAddr)
	return GenerateRegistriesYAML(zotURL, true, additional)
}

// PopulateRegistryConfig populates the RegistryConfig field in k3s.Config when
// a Zot address is available. A blank address leaves RegistryConfig empty so
// callers can detect that registries.yaml should not be written, rather than
// generating an endpoint pointing at nothing.
// This should be called when building k3s.Config for install/repair operations.
func PopulateRegistryConfig(cfg *Config, zotAddr string) {
	zotAddr = strings.TrimSpace(zotAddr)
	if zotAddr == "" {
		return
	}
	cfg.RegistryConfig = GenerateRegistriesConfig(zotAddr, cfg.AdditionalRegistries)
}

// GenerateK3sServerFlags generates the command-line flags for K3s server installation
func GenerateK3sServerFlags(cfg *Config) []string {
	flags := []string{}

	// Cluster initialization (for first control plane node in HA setup)
	if cfg.ClusterInit {
		flags = append(flags, "--cluster-init")
	}

	// Server URL (for joining additional control plane nodes)
	if cfg.ServerURL != "" {
		flags = append(flags, fmt.Sprintf("--server %s", cfg.ServerURL))
	}

	// Cluster token
	if cfg.ClusterToken != "" {
		flags = append(flags, fmt.Sprintf("--token %s", cfg.ClusterToken))
	}

	// Agent token (for workers to join)
	if cfg.AgentToken != "" {
		flags = append(flags, fmt.Sprintf("--agent-token %s", cfg.AgentToken))
	}

	// TLS SANs
	if len(cfg.TLSSANs) > 0 {
		for _, san := range cfg.TLSSANs {
			flags = append(flags, fmt.Sprintf("--tls-san %s", san))
		}
	}

	// Add the VIP as a TLS SAN whenever one is configured, even if kube-vip is
	// not deployed for it: a SAN costs nothing and keeps the certificate valid
	// if the cluster later grows a second control plane and starts using it.
	if cfg.VIP != "" {
		flags = append(flags, fmt.Sprintf("--tls-san %s", cfg.VIP))
	}

	if cfg.NodeIP != "" {
		flags = append(flags, fmt.Sprintf("--node-ip %s", cfg.NodeIP))
	}
	if cfg.FlannelIface != "" {
		flags = append(flags, fmt.Sprintf("--flannel-iface %s", cfg.FlannelIface))
	}
	if cfg.AdvertiseAddress != "" {
		flags = append(flags, fmt.Sprintf("--advertise-address %s", cfg.AdvertiseAddress))
	}

	// Disable components
	if len(cfg.DisableComponents) > 0 {
		for _, component := range cfg.DisableComponents {
			flags = append(flags, fmt.Sprintf("--disable=%s", component))
		}
	}

	// Etcd args (for tuning etcd performance in virtualized environments)
	// These are passed as --etcd-arg=<arg> to K3s
	if len(cfg.EtcdArgs) > 0 {
		for _, arg := range cfg.EtcdArgs {
			flags = append(flags, fmt.Sprintf("--etcd-arg=%s", arg))
		}
	}

	return flags
}

// GenerateK3sInstallCommand generates the full K3s installation command
func GenerateK3sInstallCommand(cfg *Config) string {
	// Base installation command
	baseCmd := "curl -sfL https://get.k3s.io | sh -s - server"

	// Add flags
	flags := GenerateK3sServerFlags(cfg)
	if len(flags) > 0 {
		baseCmd += " " + strings.Join(flags, " ")
	}

	return baseCmd
}

// GenerateResolvConfContent generates the resolv.conf content with custom DNS servers
func GenerateResolvConfContent(dnsServers []string, searchDomains []string) string {
	var lines []string

	// Add search domains
	if len(searchDomains) > 0 {
		lines = append(lines, "search "+strings.Join(searchDomains, " "))
	}

	// Add nameservers
	for _, dns := range dnsServers {
		lines = append(lines, "nameserver "+dns)
	}

	return strings.Join(lines, "\n") + "\n"
}

// GenerateSystemdResolvdConfig generates systemd-resolved configuration
// This is used to configure DNS on systems using systemd-resolved
func GenerateSystemdResolvdConfig(dnsServers []string, searchDomains []string) string {
	var lines []string

	lines = append(lines, "[Resolve]")

	// Add DNS servers
	if len(dnsServers) > 0 {
		lines = append(lines, "DNS="+strings.Join(dnsServers, " "))
	}

	// Add search domains
	if len(searchDomains) > 0 {
		lines = append(lines, "Domains="+strings.Join(searchDomains, " "))
	}

	return strings.Join(lines, "\n") + "\n"
}
